export enum ActionTypes {
  SET_MACHINE_TYPES = 'SET_MACHINE_TYPES',
  ADD_MACHINE_TYPE = 'ADD_MACHINE_TYPE',
  EDIT_MACHINE_TYPE = 'EDIT_MACHINE_TYPE',
  DELETE_MACHINE_TYPE = 'DELETE_MACHINE_TYPE',
  ADD_MACHINE = 'ADD_MACHINE',
  EDIT_MACHINE = 'EDIT_MACHINE',
  DELETE_MACHINE = 'DELETE_MACHINE',
  DELETE_ALL_MACHINE_TYPE_ITEMS = 'DELETE_ALL_MACHINE_TYPE_ITEMS',
}
