export enum ActionTypes {
  ADD_MACHINE_TYPE = 'ADD_MACHINE_TYPE',
  EDIT_MACHINE_TYPE = 'EDIT_MACHINE_TYPE',
  DELETE_MACHINE_TYPE = 'DELETE_MACHINE_TYPE',
  ADD_MACHINE = 'ADD_MACHINE',
  EDIT_MACHINE = 'EDIT_MACHINE',
  DELETE_MACHINE = 'DELETE_MACHINE',
  SET_FILTER = 'SET_FILTER',
  CLEAR_FILTER = 'CLEAR_FILTER',
}
